name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.6.1

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: programa
          
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: lucaslima582
        password: Rammstein123@#

    - name: Build and Push Docker Images
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        file: ./Dockerfile   
        push: true
        tags: lucaslima582/go_ci:${{ github.ref_name }}
